name: aviationwiki
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_html: ^0.11.1
  intl: ^0.16.1
  webfeed: ^0.4.2
  http: ^0.12.0+4
  cached_network_image: ^2.1.0+1

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
  - assets/images/logo.png
  - assets/images/no_img.png